(defun compress (lst)
  (if (null lst)
      '()
    (let ((compressed (list (first lst))))
      (dolist (elem (rest lst) compressed)
        (if (not (equal (first compressed) elem))
            (push elem compressed)))))) 
